/*
* MIT License

* Copyright (c) 2023 Aspose Pty Ltd

* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:

* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.

* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

import { Configuration } from './Configuration';
import { HttpClient, HttpOptions, HttpResponse, HttpResult } from './httpClient';

import {
    ApiError,
    ApiErrorResponse,
    AustralianPostParams,
    AutoSizeMode,
    AvailableGraphicsUnit,
    AztecParams,
    AztecSymbolMode,
    BarcodeResponse,
    BarcodeResponseList,
    BorderDashStyle,
    CaptionParams,
    ChecksumValidation,
    CodabarChecksumMode,
    CodabarParams,
    CodabarSymbol,
    CodablockParams,
    Code128Emulation,
    Code16KParams,
    CodeLocation,
    CouponParams,
    CustomerInformationInterpretingType,
    DataBarParams,
    DataMatrixEccType,
    DataMatrixEncodeMode,
    DataMatrixParams,
    DecodeBarcodeType,
    DiscUsage,
    DotCodeEncodeMode,
    DotCodeParams,
    ECIEncodings,
    EnableChecksum,
    EncodeBarcodeType,
    ErrorDetails,
    FileVersion,
    FileVersions,
    FilesList,
    FilesUploadResult,
    FontMode,
    FontParams,
    FontStyle,
    GeneratorParams,
    GeneratorParamsList,
    ITF14BorderType,
    ITFParams,
    MacroCharacter,
    MaxiCodeEncodeMode,
    MaxiCodeMode,
    MaxiCodeParams,
    ModelError,
    ObjectExist,
    Padding,
    PatchCodeParams,
    PatchFormat,
    Pdf417CompactionMode,
    Pdf417ErrorLevel,
    Pdf417MacroTerminator,
    Pdf417Params,
    PostalParams,
    PresetType,
    QREncodeMode,
    QREncodeType,
    QRErrorLevel,
    QRVersion,
    QrParams,
    ReaderParams,
    RegionPoint,
    ResultImageInfo,
    StorageExist,
    StorageFile,
    StructuredAppend,
    TextAlignment,
} from './models';

import {
    GetBarcodeGenerateRequest,
    GetBarcodeRecognizeRequest,
    PostBarcodeRecognizeFromUrlOrContentRequest,
    PostGenerateMultipleRequest,
    PutBarcodeGenerateFileRequest,
    PutBarcodeRecognizeFromBodyRequest,
    PutGenerateMultipleRequest,
    CopyFileRequest,
    DeleteFileRequest,
    DownloadFileRequest,
    MoveFileRequest,
    UploadFileRequest,
    CopyFolderRequest,
    CreateFolderRequest,
    DeleteFolderRequest,
    GetFilesListRequest,
    MoveFolderRequest,
    GetDiscUsageRequest,
    GetFileVersionsRequest,
    ObjectExistsRequest,
    StorageExistsRequest,
} from './models';

export * from './models';

let primitives = ['string', 'boolean', 'double', 'integer', 'long', 'float', 'number', 'any'];

class ObjectSerializer {
    public static findCorrectType(data: any, expectedType: string) {
        if (data == null) {
            return expectedType;
        }

        if (primitives.indexOf(expectedType.toLowerCase()) !== -1) {
            return expectedType;
        }

        if (expectedType === 'Date') {
            return expectedType;
        }

        if (enumsMap[expectedType]) {
            return expectedType;
        }

        if (!typeMap[expectedType]) {
            return expectedType; // w/e we don't know the type
        }

        // Check the discriminator
        let discriminatorProperty = typeMap[expectedType].discriminator;
        if (discriminatorProperty == null) {
            return expectedType; // the type does not have a discriminator. use it.
        }

        if (data[discriminatorProperty]) {
            return data[discriminatorProperty]; // use the type given in the discriminator
        }

        return expectedType; // discriminator was not present (or an empty string)
    }

    public static serialize(data: any, type: string) {
        if (data == null) {
            return data;
        }

        if (primitives.indexOf(type.toLowerCase()) !== -1) {
            return data;
        }

        if (type.lastIndexOf('Array<', 0) === 0) {
            // string.startsWith pre es6
            let subType: string = type.replace('Array<', ''); // Array<Type> => Type>
            subType = subType.substring(0, subType.length - 1); // Type> => Type
            let transformedData: any[] = [];
            for (let index in data) {
                let date = data[index];
                transformedData.push(ObjectSerializer.serialize(date, subType));
            }

            return transformedData;
        }

        if (type === 'Date') {
            return data.toString();
        }

        if (enumsMap[type]) {
            return enumsMap[type][data];
        }

        if (!typeMap[type]) {
            // in case we don't know the type
            return data;
        }

        // get the map for the correct type.
        let attributeTypes = typeMap[type].getAttributeTypeMap();
        let instance: { [index: string]: any } = {};
        for (let index in attributeTypes) {
            let attributeType = attributeTypes[index];
            instance[attributeType.baseName] = ObjectSerializer.serialize(data[attributeType.name], attributeType.type);
        }

        return instance;
    }

    public static deserialize(data: any, type: string) {
        // polymorphism may change the actual type.
        type = ObjectSerializer.findCorrectType(data, type);

        if (data == null) {
            return data;
        }

        if (primitives.indexOf(type.toLowerCase()) !== -1) {
            return data;
        }

        if (type.lastIndexOf('Array<', 0) === 0) {
            // string.startsWith pre es6
            let subType: string = type.replace('Array<', ''); // Array<Type> => Type>
            subType = subType.substring(0, subType.length - 1); // Type> => Type
            let transformedData: any[] = [];
            for (let index in data) {
                let date = data[index];
                transformedData.push(ObjectSerializer.deserialize(date, subType));
            }
            return transformedData;
        }

        if (type === 'Date') {
            return new Date(data);
        }

        if (enumsMap[type]) {
            // is Enum
            return data;
        }

        if (!typeMap[type]) {
            // don't know the type
            return data;
        }

        if (typeof data === 'string') {
            // data should be deserialized before usage
            data = JSON.parse(data);
        }

        let instance = new typeMap[type]();
        let attributeTypes = typeMap[type].getAttributeTypeMap();
        for (const attributeType of attributeTypes) {
            const key = attributeType.baseName.replace(/^(.)/, ($1: string) => {
                return $1.toLowerCase();
            });
            instance[attributeType.name] = ObjectSerializer.deserialize(data[key], attributeType.type);
        }

        return instance;
    }
}

let enumsMap: { [index: string]: any } = {
    AutoSizeMode: AutoSizeMode,
    AvailableGraphicsUnit: AvailableGraphicsUnit,
    AztecSymbolMode: AztecSymbolMode,
    BorderDashStyle: BorderDashStyle,
    ChecksumValidation: ChecksumValidation,
    CodabarChecksumMode: CodabarChecksumMode,
    CodabarSymbol: CodabarSymbol,
    Code128Emulation: Code128Emulation,
    CodeLocation: CodeLocation,
    CustomerInformationInterpretingType: CustomerInformationInterpretingType,
    DataMatrixEccType: DataMatrixEccType,
    DataMatrixEncodeMode: DataMatrixEncodeMode,
    DecodeBarcodeType: DecodeBarcodeType,
    DotCodeEncodeMode: DotCodeEncodeMode,
    ECIEncodings: ECIEncodings,
    EnableChecksum: EnableChecksum,
    EncodeBarcodeType: EncodeBarcodeType,
    FontMode: FontMode,
    FontStyle: FontStyle,
    ITF14BorderType: ITF14BorderType,
    MacroCharacter: MacroCharacter,
    MaxiCodeEncodeMode: MaxiCodeEncodeMode,
    MaxiCodeMode: MaxiCodeMode,
    PatchFormat: PatchFormat,
    Pdf417CompactionMode: Pdf417CompactionMode,
    Pdf417ErrorLevel: Pdf417ErrorLevel,
    Pdf417MacroTerminator: Pdf417MacroTerminator,
    PresetType: PresetType,
    QREncodeMode: QREncodeMode,
    QREncodeType: QREncodeType,
    QRErrorLevel: QRErrorLevel,
    QRVersion: QRVersion,
    TextAlignment: TextAlignment,
};

let typeMap: { [index: string]: any } = {
    ApiError: ApiError,
    ApiErrorResponse: ApiErrorResponse,
    AustralianPostParams: AustralianPostParams,
    AztecParams: AztecParams,
    BarcodeResponse: BarcodeResponse,
    BarcodeResponseList: BarcodeResponseList,
    CaptionParams: CaptionParams,
    CodabarParams: CodabarParams,
    CodablockParams: CodablockParams,
    Code16KParams: Code16KParams,
    CouponParams: CouponParams,
    DataBarParams: DataBarParams,
    DataMatrixParams: DataMatrixParams,
    DiscUsage: DiscUsage,
    DotCodeParams: DotCodeParams,
    ErrorDetails: ErrorDetails,
    FileVersion: FileVersion,
    FileVersions: FileVersions,
    FilesList: FilesList,
    FilesUploadResult: FilesUploadResult,
    FontParams: FontParams,
    GeneratorParams: GeneratorParams,
    GeneratorParamsList: GeneratorParamsList,
    ITFParams: ITFParams,
    MaxiCodeParams: MaxiCodeParams,
    ModelError: ModelError,
    ObjectExist: ObjectExist,
    Padding: Padding,
    PatchCodeParams: PatchCodeParams,
    Pdf417Params: Pdf417Params,
    PostalParams: PostalParams,
    QrParams: QrParams,
    ReaderParams: ReaderParams,
    RegionPoint: RegionPoint,
    ResultImageInfo: ResultImageInfo,
    StorageExist: StorageExist,
    StorageFile: StorageFile,
    StructuredAppend: StructuredAppend,
};

export class BarcodeApi {
    protected defaultHeaders: any = {};
    protected _configuration: Configuration;
    private _client: HttpClient;

    constructor(configuration: Configuration) {
        this._configuration = configuration;
        this._client = new HttpClient();
    }

    /**
     *
     * @summary Generate barcode.
     * @param request GetBarcodeGenerateRequest
     */
    public async getBarcodeGenerate(
        request: GetBarcodeGenerateRequest
    ): Promise<{ response: HttpResponse; body: Buffer }> {
        const requestPath = this._configuration.getApiBaseUrl() + '/barcode/generate';
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.type' is not null or undefined
        if (request.type == null) {
            throw new Error('Required parameter request.type was null or undefined when calling getBarcodeGenerate.');
        }

        // verify required parameter 'request.text' is not null or undefined
        if (request.text == null) {
            throw new Error('Required parameter request.text was null or undefined when calling getBarcodeGenerate.');
        }

        if (request.type != null) {
            requestQueryParameters['Type'] = ObjectSerializer.serialize(
                request.type,
                "'Codabar' | 'Code11' | 'Code39Standard' | 'Code39Extended' | 'Code93Standard' | 'Code93Extended' | 'Code128' | 'GS1Code128' | 'EAN8' | 'EAN13' | 'EAN14' | 'SCC14' | 'SSCC18' | 'UPCA' | 'UPCE' | 'ISBN' | 'ISSN' | 'ISMN' | 'Standard2of5' | 'Interleaved2of5' | 'Matrix2of5' | 'ItalianPost25' | 'IATA2of5' | 'ITF14' | 'ITF6' | 'MSI' | 'VIN' | 'DeutschePostIdentcode' | 'DeutschePostLeitcode' | 'OPC' | 'PZN' | 'Code16K' | 'Pharmacode' | 'DataMatrix' | 'QR' | 'Aztec' | 'Pdf417' | 'MacroPdf417' | 'AustraliaPost' | 'Postnet' | 'Planet' | 'OneCode' | 'RM4SCC' | 'DatabarOmniDirectional' | 'DatabarTruncated' | 'DatabarLimited' | 'DatabarExpanded' | 'SingaporePost' | 'GS1DataMatrix' | 'AustralianPosteParcel' | 'SwissPostParcel' | 'PatchCode' | 'DatabarExpandedStacked' | 'DatabarStacked' | 'DatabarStackedOmniDirectional' | 'MicroPdf417' | 'GS1QR' | 'MaxiCode' | 'Code32' | 'DataLogic2of5' | 'DotCode' | 'DutchKIX' | 'UpcaGs1Code128Coupon' | 'UpcaGs1DatabarCoupon' | 'CodablockF' | 'GS1CodablockF' | 'Mailmark' | 'GS1DotCode'"
            );
        }

        if (request.text != null) {
            requestQueryParameters['Text'] = ObjectSerializer.serialize(request.text, 'string');
        }

        if (request.twoDDisplayText != null) {
            requestQueryParameters['TwoDDisplayText'] = ObjectSerializer.serialize(request.twoDDisplayText, 'string');
        }

        if (request.textLocation != null) {
            requestQueryParameters['TextLocation'] = ObjectSerializer.serialize(
                request.textLocation,
                "'Below' | 'Above' | 'None'"
            );
        }

        if (request.textAlignment != null) {
            requestQueryParameters['TextAlignment'] = ObjectSerializer.serialize(
                request.textAlignment,
                "'Left' | 'Center' | 'Right'"
            );
        }

        if (request.textColor != null) {
            requestQueryParameters['TextColor'] = ObjectSerializer.serialize(request.textColor, 'string');
        }

        if (request.fontSizeMode != null) {
            requestQueryParameters['FontSizeMode'] = ObjectSerializer.serialize(
                request.fontSizeMode,
                "'Auto' | 'Manual'"
            );
        }

        if (request.noWrap != null) {
            requestQueryParameters['NoWrap'] = ObjectSerializer.serialize(request.noWrap, 'boolean');
        }

        if (request.resolution != null) {
            requestQueryParameters['Resolution'] = ObjectSerializer.serialize(request.resolution, 'number');
        }

        if (request.resolutionX != null) {
            requestQueryParameters['ResolutionX'] = ObjectSerializer.serialize(request.resolutionX, 'number');
        }

        if (request.resolutionY != null) {
            requestQueryParameters['ResolutionY'] = ObjectSerializer.serialize(request.resolutionY, 'number');
        }

        if (request.dimensionX != null) {
            requestQueryParameters['DimensionX'] = ObjectSerializer.serialize(request.dimensionX, 'number');
        }

        if (request.textSpace != null) {
            requestQueryParameters['TextSpace'] = ObjectSerializer.serialize(request.textSpace, 'number');
        }

        if (request.units != null) {
            requestQueryParameters['Units'] = ObjectSerializer.serialize(
                request.units,
                "'Pixel' | 'Point' | 'Inch' | 'Millimeter'"
            );
        }

        if (request.sizeMode != null) {
            requestQueryParameters['SizeMode'] = ObjectSerializer.serialize(
                request.sizeMode,
                "'None' | 'Nearest' | 'Interpolation'"
            );
        }

        if (request.barHeight != null) {
            requestQueryParameters['BarHeight'] = ObjectSerializer.serialize(request.barHeight, 'number');
        }

        if (request.imageHeight != null) {
            requestQueryParameters['ImageHeight'] = ObjectSerializer.serialize(request.imageHeight, 'number');
        }

        if (request.imageWidth != null) {
            requestQueryParameters['ImageWidth'] = ObjectSerializer.serialize(request.imageWidth, 'number');
        }

        if (request.rotationAngle != null) {
            requestQueryParameters['RotationAngle'] = ObjectSerializer.serialize(request.rotationAngle, 'number');
        }

        if (request.backColor != null) {
            requestQueryParameters['BackColor'] = ObjectSerializer.serialize(request.backColor, 'string');
        }

        if (request.barColor != null) {
            requestQueryParameters['BarColor'] = ObjectSerializer.serialize(request.barColor, 'string');
        }

        if (request.borderColor != null) {
            requestQueryParameters['BorderColor'] = ObjectSerializer.serialize(request.borderColor, 'string');
        }

        if (request.borderWidth != null) {
            requestQueryParameters['BorderWidth'] = ObjectSerializer.serialize(request.borderWidth, 'number');
        }

        if (request.borderDashStyle != null) {
            requestQueryParameters['BorderDashStyle'] = ObjectSerializer.serialize(
                request.borderDashStyle,
                "'Solid' | 'Dash' | 'Dot' | 'DashDot' | 'DashDotDot'"
            );
        }

        if (request.borderVisible != null) {
            requestQueryParameters['BorderVisible'] = ObjectSerializer.serialize(request.borderVisible, 'boolean');
        }

        if (request.enableChecksum != null) {
            requestQueryParameters['EnableChecksum'] = ObjectSerializer.serialize(
                request.enableChecksum,
                "'Default' | 'Yes' | 'No'"
            );
        }

        if (request.enableEscape != null) {
            requestQueryParameters['EnableEscape'] = ObjectSerializer.serialize(request.enableEscape, 'boolean');
        }

        if (request.filledBars != null) {
            requestQueryParameters['FilledBars'] = ObjectSerializer.serialize(request.filledBars, 'boolean');
        }

        if (request.alwaysShowChecksum != null) {
            requestQueryParameters['AlwaysShowChecksum'] = ObjectSerializer.serialize(
                request.alwaysShowChecksum,
                'boolean'
            );
        }

        if (request.wideNarrowRatio != null) {
            requestQueryParameters['WideNarrowRatio'] = ObjectSerializer.serialize(request.wideNarrowRatio, 'number');
        }

        if (request.validateText != null) {
            requestQueryParameters['ValidateText'] = ObjectSerializer.serialize(request.validateText, 'boolean');
        }

        if (request.supplementData != null) {
            requestQueryParameters['SupplementData'] = ObjectSerializer.serialize(request.supplementData, 'string');
        }

        if (request.supplementSpace != null) {
            requestQueryParameters['SupplementSpace'] = ObjectSerializer.serialize(request.supplementSpace, 'number');
        }

        if (request.barWidthReduction != null) {
            requestQueryParameters['BarWidthReduction'] = ObjectSerializer.serialize(
                request.barWidthReduction,
                'number'
            );
        }

        if (request.useAntiAlias != null) {
            requestQueryParameters['UseAntiAlias'] = ObjectSerializer.serialize(request.useAntiAlias, 'boolean');
        }

        if (request.format != null) {
            requestQueryParameters['format'] = ObjectSerializer.serialize(request.format, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            encoding: null,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'Buffer'),
        };
    }

    /**
     *
     * @summary Recognize barcode from a file on server.
     * @param request GetBarcodeRecognizeRequest
     */
    public async getBarcodeRecognize(
        request: GetBarcodeRecognizeRequest
    ): Promise<{ response: HttpResponse; body: BarcodeResponseList }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/{name}/recognize'.replace('{' + 'name' + '}', String(request.name));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.name' is not null or undefined
        if (request.name == null) {
            throw new Error('Required parameter request.name was null or undefined when calling getBarcodeRecognize.');
        }

        if (request.type != null) {
            requestQueryParameters['Type'] = ObjectSerializer.serialize(
                request.type,
                "'all' | 'AustraliaPost' | 'Aztec' | 'ISBN' | 'Codabar' | 'Code11' | 'Code128' | 'GS1Code128' | 'Code39Extended' | 'Code39Standard' | 'Code93Extended' | 'Code93Standard' | 'DataMatrix' | 'DeutschePostIdentcode' | 'DeutschePostLeitcode' | 'EAN13' | 'EAN14' | 'EAN8' | 'IATA2of5' | 'Interleaved2of5' | 'ISSN' | 'ISMN' | 'ItalianPost25' | 'ITF14' | 'ITF6' | 'MacroPdf417' | 'Matrix2of5' | 'MSI' | 'OneCode' | 'OPC' | 'PatchCode' | 'Pdf417' | 'MicroPdf417' | 'Planet' | 'Postnet' | 'PZN' | 'QR' | 'MicroQR' | 'RM4SCC' | 'SCC14' | 'SSCC18' | 'Standard2of5' | 'Supplement' | 'UPCA' | 'UPCE' | 'VIN' | 'Pharmacode' | 'GS1DataMatrix' | 'DatabarOmniDirectional' | 'DatabarTruncated' | 'DatabarLimited' | 'DatabarExpanded' | 'SwissPostParcel' | 'AustralianPosteParcel' | 'Code16K' | 'DatabarStackedOmniDirectional' | 'DatabarStacked' | 'DatabarExpandedStacked' | 'CompactPdf417' | 'GS1QR' | 'MaxiCode' | 'MicrE13B' | 'Code32' | 'DataLogic2of5' | 'DotCode' | 'DutchKIX' | 'CodablockF' | 'Mailmark' | 'GS1DotCode' | 'HIBCCode39LIC' | 'HIBCCode128LIC' | 'HIBCAztecLIC' | 'HIBCDataMatrixLIC' | 'HIBCQRLIC' | 'HIBCCode39PAS' | 'HIBCCode128PAS' | 'HIBCAztecPAS' | 'HIBCDataMatrixPAS' | 'HIBCQRPAS'"
            );
        }

        if (request.checksumValidation != null) {
            requestQueryParameters['ChecksumValidation'] = ObjectSerializer.serialize(
                request.checksumValidation,
                "'Default' | 'On' | 'Off'"
            );
        }

        if (request.detectEncoding != null) {
            requestQueryParameters['DetectEncoding'] = ObjectSerializer.serialize(request.detectEncoding, 'boolean');
        }

        if (request.preset != null) {
            requestQueryParameters['Preset'] = ObjectSerializer.serialize(
                request.preset,
                "'HighPerformance' | 'NormalQuality' | 'HighQualityDetection' | 'MaxQualityDetection' | 'HighQuality' | 'MaxBarCodes'"
            );
        }

        if (request.rectX != null) {
            requestQueryParameters['RectX'] = ObjectSerializer.serialize(request.rectX, 'number');
        }

        if (request.rectY != null) {
            requestQueryParameters['RectY'] = ObjectSerializer.serialize(request.rectY, 'number');
        }

        if (request.rectWidth != null) {
            requestQueryParameters['RectWidth'] = ObjectSerializer.serialize(request.rectWidth, 'number');
        }

        if (request.rectHeight != null) {
            requestQueryParameters['RectHeight'] = ObjectSerializer.serialize(request.rectHeight, 'number');
        }

        if (request.stripFNC != null) {
            requestQueryParameters['StripFNC'] = ObjectSerializer.serialize(request.stripFNC, 'boolean');
        }

        if (request.timeout != null) {
            requestQueryParameters['Timeout'] = ObjectSerializer.serialize(request.timeout, 'number');
        }

        if (request.medianSmoothingWindowSize != null) {
            requestQueryParameters['MedianSmoothingWindowSize'] = ObjectSerializer.serialize(
                request.medianSmoothingWindowSize,
                'number'
            );
        }

        if (request.allowMedianSmoothing != null) {
            requestQueryParameters['AllowMedianSmoothing'] = ObjectSerializer.serialize(
                request.allowMedianSmoothing,
                'boolean'
            );
        }

        if (request.allowComplexBackground != null) {
            requestQueryParameters['AllowComplexBackground'] = ObjectSerializer.serialize(
                request.allowComplexBackground,
                'boolean'
            );
        }

        if (request.allowDatamatrixIndustrialBarcodes != null) {
            requestQueryParameters['AllowDatamatrixIndustrialBarcodes'] = ObjectSerializer.serialize(
                request.allowDatamatrixIndustrialBarcodes,
                'boolean'
            );
        }

        if (request.allowDecreasedImage != null) {
            requestQueryParameters['AllowDecreasedImage'] = ObjectSerializer.serialize(
                request.allowDecreasedImage,
                'boolean'
            );
        }

        if (request.allowDetectScanGap != null) {
            requestQueryParameters['AllowDetectScanGap'] = ObjectSerializer.serialize(
                request.allowDetectScanGap,
                'boolean'
            );
        }

        if (request.allowIncorrectBarcodes != null) {
            requestQueryParameters['AllowIncorrectBarcodes'] = ObjectSerializer.serialize(
                request.allowIncorrectBarcodes,
                'boolean'
            );
        }

        if (request.allowInvertImage != null) {
            requestQueryParameters['AllowInvertImage'] = ObjectSerializer.serialize(
                request.allowInvertImage,
                'boolean'
            );
        }

        if (request.allowMicroWhiteSpotsRemoving != null) {
            requestQueryParameters['AllowMicroWhiteSpotsRemoving'] = ObjectSerializer.serialize(
                request.allowMicroWhiteSpotsRemoving,
                'boolean'
            );
        }

        if (request.allowOneDFastBarcodesDetector != null) {
            requestQueryParameters['AllowOneDFastBarcodesDetector'] = ObjectSerializer.serialize(
                request.allowOneDFastBarcodesDetector,
                'boolean'
            );
        }

        if (request.allowOneDWipedBarsRestoration != null) {
            requestQueryParameters['AllowOneDWipedBarsRestoration'] = ObjectSerializer.serialize(
                request.allowOneDWipedBarsRestoration,
                'boolean'
            );
        }

        if (request.allowQRMicroQrRestoration != null) {
            requestQueryParameters['AllowQRMicroQrRestoration'] = ObjectSerializer.serialize(
                request.allowQRMicroQrRestoration,
                'boolean'
            );
        }

        if (request.allowRegularImage != null) {
            requestQueryParameters['AllowRegularImage'] = ObjectSerializer.serialize(
                request.allowRegularImage,
                'boolean'
            );
        }

        if (request.allowSaltAndPepperFiltering != null) {
            requestQueryParameters['AllowSaltAndPepperFiltering'] = ObjectSerializer.serialize(
                request.allowSaltAndPepperFiltering,
                'boolean'
            );
        }

        if (request.allowWhiteSpotsRemoving != null) {
            requestQueryParameters['AllowWhiteSpotsRemoving'] = ObjectSerializer.serialize(
                request.allowWhiteSpotsRemoving,
                'boolean'
            );
        }

        if (request.checkMore1DVariants != null) {
            requestQueryParameters['CheckMore1DVariants'] = ObjectSerializer.serialize(
                request.checkMore1DVariants,
                'boolean'
            );
        }

        if (request.fastScanOnly != null) {
            requestQueryParameters['FastScanOnly'] = ObjectSerializer.serialize(request.fastScanOnly, 'boolean');
        }

        if (request.regionLikelihoodThresholdPercent != null) {
            requestQueryParameters['RegionLikelihoodThresholdPercent'] = ObjectSerializer.serialize(
                request.regionLikelihoodThresholdPercent,
                'number'
            );
        }

        if (request.scanWindowSizes != null) {
            requestQueryParameters['ScanWindowSizes'] = ObjectSerializer.serialize(
                request.scanWindowSizes,
                'Array<number>'
            );
        }

        if (request.similarity != null) {
            requestQueryParameters['Similarity'] = ObjectSerializer.serialize(request.similarity, 'number');
        }

        if (request.skipDiagonalSearch != null) {
            requestQueryParameters['SkipDiagonalSearch'] = ObjectSerializer.serialize(
                request.skipDiagonalSearch,
                'boolean'
            );
        }

        if (request.readTinyBarcodes != null) {
            requestQueryParameters['ReadTinyBarcodes'] = ObjectSerializer.serialize(
                request.readTinyBarcodes,
                'boolean'
            );
        }

        if (request.australianPostEncodingTable != null) {
            requestQueryParameters['AustralianPostEncodingTable'] = ObjectSerializer.serialize(
                request.australianPostEncodingTable,
                "'CTable' | 'NTable' | 'Other'"
            );
        }

        if (request.ignoreEndingFillingPatternsForCTable != null) {
            requestQueryParameters['IgnoreEndingFillingPatternsForCTable'] = ObjectSerializer.serialize(
                request.ignoreEndingFillingPatternsForCTable,
                'boolean'
            );
        }

        if (request.storage != null) {
            requestQueryParameters['storage'] = ObjectSerializer.serialize(request.storage, 'string');
        }

        if (request.folder != null) {
            requestQueryParameters['folder'] = ObjectSerializer.serialize(request.folder, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'BarcodeResponseList'),
        };
    }

    /**
     *
     * @summary Recognize barcode from an url or from request body. Request body can contain raw data bytes of the image with content-type \"application/octet-stream\". An image can also be passed as a form field.
     * @param request PostBarcodeRecognizeFromUrlOrContentRequest
     */
    public async postBarcodeRecognizeFromUrlOrContent(
        request: PostBarcodeRecognizeFromUrlOrContentRequest
    ): Promise<{ response: HttpResponse; body: BarcodeResponseList }> {
        const requestPath = this._configuration.getApiBaseUrl() + '/barcode/recognize';
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);
        let requestFormParams: any = {};

        if (request.type != null) {
            requestQueryParameters['Type'] = ObjectSerializer.serialize(
                request.type,
                "'all' | 'AustraliaPost' | 'Aztec' | 'ISBN' | 'Codabar' | 'Code11' | 'Code128' | 'GS1Code128' | 'Code39Extended' | 'Code39Standard' | 'Code93Extended' | 'Code93Standard' | 'DataMatrix' | 'DeutschePostIdentcode' | 'DeutschePostLeitcode' | 'EAN13' | 'EAN14' | 'EAN8' | 'IATA2of5' | 'Interleaved2of5' | 'ISSN' | 'ISMN' | 'ItalianPost25' | 'ITF14' | 'ITF6' | 'MacroPdf417' | 'Matrix2of5' | 'MSI' | 'OneCode' | 'OPC' | 'PatchCode' | 'Pdf417' | 'MicroPdf417' | 'Planet' | 'Postnet' | 'PZN' | 'QR' | 'MicroQR' | 'RM4SCC' | 'SCC14' | 'SSCC18' | 'Standard2of5' | 'Supplement' | 'UPCA' | 'UPCE' | 'VIN' | 'Pharmacode' | 'GS1DataMatrix' | 'DatabarOmniDirectional' | 'DatabarTruncated' | 'DatabarLimited' | 'DatabarExpanded' | 'SwissPostParcel' | 'AustralianPosteParcel' | 'Code16K' | 'DatabarStackedOmniDirectional' | 'DatabarStacked' | 'DatabarExpandedStacked' | 'CompactPdf417' | 'GS1QR' | 'MaxiCode' | 'MicrE13B' | 'Code32' | 'DataLogic2of5' | 'DotCode' | 'DutchKIX' | 'CodablockF' | 'Mailmark' | 'GS1DotCode' | 'HIBCCode39LIC' | 'HIBCCode128LIC' | 'HIBCAztecLIC' | 'HIBCDataMatrixLIC' | 'HIBCQRLIC' | 'HIBCCode39PAS' | 'HIBCCode128PAS' | 'HIBCAztecPAS' | 'HIBCDataMatrixPAS' | 'HIBCQRPAS'"
            );
        }

        if (request.checksumValidation != null) {
            requestQueryParameters['ChecksumValidation'] = ObjectSerializer.serialize(
                request.checksumValidation,
                "'Default' | 'On' | 'Off'"
            );
        }

        if (request.detectEncoding != null) {
            requestQueryParameters['DetectEncoding'] = ObjectSerializer.serialize(request.detectEncoding, 'boolean');
        }

        if (request.preset != null) {
            requestQueryParameters['Preset'] = ObjectSerializer.serialize(
                request.preset,
                "'HighPerformance' | 'NormalQuality' | 'HighQualityDetection' | 'MaxQualityDetection' | 'HighQuality' | 'MaxBarCodes'"
            );
        }

        if (request.rectX != null) {
            requestQueryParameters['RectX'] = ObjectSerializer.serialize(request.rectX, 'number');
        }

        if (request.rectY != null) {
            requestQueryParameters['RectY'] = ObjectSerializer.serialize(request.rectY, 'number');
        }

        if (request.rectWidth != null) {
            requestQueryParameters['RectWidth'] = ObjectSerializer.serialize(request.rectWidth, 'number');
        }

        if (request.rectHeight != null) {
            requestQueryParameters['RectHeight'] = ObjectSerializer.serialize(request.rectHeight, 'number');
        }

        if (request.stripFNC != null) {
            requestQueryParameters['StripFNC'] = ObjectSerializer.serialize(request.stripFNC, 'boolean');
        }

        if (request.timeout != null) {
            requestQueryParameters['Timeout'] = ObjectSerializer.serialize(request.timeout, 'number');
        }

        if (request.medianSmoothingWindowSize != null) {
            requestQueryParameters['MedianSmoothingWindowSize'] = ObjectSerializer.serialize(
                request.medianSmoothingWindowSize,
                'number'
            );
        }

        if (request.allowMedianSmoothing != null) {
            requestQueryParameters['AllowMedianSmoothing'] = ObjectSerializer.serialize(
                request.allowMedianSmoothing,
                'boolean'
            );
        }

        if (request.allowComplexBackground != null) {
            requestQueryParameters['AllowComplexBackground'] = ObjectSerializer.serialize(
                request.allowComplexBackground,
                'boolean'
            );
        }

        if (request.allowDatamatrixIndustrialBarcodes != null) {
            requestQueryParameters['AllowDatamatrixIndustrialBarcodes'] = ObjectSerializer.serialize(
                request.allowDatamatrixIndustrialBarcodes,
                'boolean'
            );
        }

        if (request.allowDecreasedImage != null) {
            requestQueryParameters['AllowDecreasedImage'] = ObjectSerializer.serialize(
                request.allowDecreasedImage,
                'boolean'
            );
        }

        if (request.allowDetectScanGap != null) {
            requestQueryParameters['AllowDetectScanGap'] = ObjectSerializer.serialize(
                request.allowDetectScanGap,
                'boolean'
            );
        }

        if (request.allowIncorrectBarcodes != null) {
            requestQueryParameters['AllowIncorrectBarcodes'] = ObjectSerializer.serialize(
                request.allowIncorrectBarcodes,
                'boolean'
            );
        }

        if (request.allowInvertImage != null) {
            requestQueryParameters['AllowInvertImage'] = ObjectSerializer.serialize(
                request.allowInvertImage,
                'boolean'
            );
        }

        if (request.allowMicroWhiteSpotsRemoving != null) {
            requestQueryParameters['AllowMicroWhiteSpotsRemoving'] = ObjectSerializer.serialize(
                request.allowMicroWhiteSpotsRemoving,
                'boolean'
            );
        }

        if (request.allowOneDFastBarcodesDetector != null) {
            requestQueryParameters['AllowOneDFastBarcodesDetector'] = ObjectSerializer.serialize(
                request.allowOneDFastBarcodesDetector,
                'boolean'
            );
        }

        if (request.allowOneDWipedBarsRestoration != null) {
            requestQueryParameters['AllowOneDWipedBarsRestoration'] = ObjectSerializer.serialize(
                request.allowOneDWipedBarsRestoration,
                'boolean'
            );
        }

        if (request.allowQRMicroQrRestoration != null) {
            requestQueryParameters['AllowQRMicroQrRestoration'] = ObjectSerializer.serialize(
                request.allowQRMicroQrRestoration,
                'boolean'
            );
        }

        if (request.allowRegularImage != null) {
            requestQueryParameters['AllowRegularImage'] = ObjectSerializer.serialize(
                request.allowRegularImage,
                'boolean'
            );
        }

        if (request.allowSaltAndPepperFiltering != null) {
            requestQueryParameters['AllowSaltAndPepperFiltering'] = ObjectSerializer.serialize(
                request.allowSaltAndPepperFiltering,
                'boolean'
            );
        }

        if (request.allowWhiteSpotsRemoving != null) {
            requestQueryParameters['AllowWhiteSpotsRemoving'] = ObjectSerializer.serialize(
                request.allowWhiteSpotsRemoving,
                'boolean'
            );
        }

        if (request.checkMore1DVariants != null) {
            requestQueryParameters['CheckMore1DVariants'] = ObjectSerializer.serialize(
                request.checkMore1DVariants,
                'boolean'
            );
        }

        if (request.fastScanOnly != null) {
            requestQueryParameters['FastScanOnly'] = ObjectSerializer.serialize(request.fastScanOnly, 'boolean');
        }

        if (request.regionLikelihoodThresholdPercent != null) {
            requestQueryParameters['RegionLikelihoodThresholdPercent'] = ObjectSerializer.serialize(
                request.regionLikelihoodThresholdPercent,
                'number'
            );
        }

        if (request.scanWindowSizes != null) {
            requestQueryParameters['ScanWindowSizes'] = ObjectSerializer.serialize(
                request.scanWindowSizes,
                'Array<number>'
            );
        }

        if (request.similarity != null) {
            requestQueryParameters['Similarity'] = ObjectSerializer.serialize(request.similarity, 'number');
        }

        if (request.skipDiagonalSearch != null) {
            requestQueryParameters['SkipDiagonalSearch'] = ObjectSerializer.serialize(
                request.skipDiagonalSearch,
                'boolean'
            );
        }

        if (request.readTinyBarcodes != null) {
            requestQueryParameters['ReadTinyBarcodes'] = ObjectSerializer.serialize(
                request.readTinyBarcodes,
                'boolean'
            );
        }

        if (request.australianPostEncodingTable != null) {
            requestQueryParameters['AustralianPostEncodingTable'] = ObjectSerializer.serialize(
                request.australianPostEncodingTable,
                "'CTable' | 'NTable' | 'Other'"
            );
        }

        if (request.ignoreEndingFillingPatternsForCTable != null) {
            requestQueryParameters['IgnoreEndingFillingPatternsForCTable'] = ObjectSerializer.serialize(
                request.ignoreEndingFillingPatternsForCTable,
                'boolean'
            );
        }

        if (request.url != null) {
            requestQueryParameters['url'] = ObjectSerializer.serialize(request.url, 'string');
        }

        if (request.image != null) {
            requestFormParams['image'] = request.image;
        }

        let requestOptions: HttpOptions = {
            method: 'POST',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            body: request.image,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'BarcodeResponseList'),
        };
    }

    /**
     *
     * @summary Generate multiple barcodes and return in response stream
     * @param request PostGenerateMultipleRequest
     */
    public async postGenerateMultiple(
        request: PostGenerateMultipleRequest
    ): Promise<{ response: HttpResponse; body: Buffer }> {
        const requestPath = this._configuration.getApiBaseUrl() + '/barcode/generateMultiple';
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.generatorParamsList' is not null or undefined
        if (request.generatorParamsList == null) {
            throw new Error(
                'Required parameter request.generatorParamsList was null or undefined when calling postGenerateMultiple.'
            );
        }

        if (request.format != null) {
            requestQueryParameters['format'] = ObjectSerializer.serialize(request.format, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'POST',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            body: ObjectSerializer.serialize(request.generatorParamsList, 'GeneratorParamsList'),
            json: true,
            encoding: null,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'Buffer'),
        };
    }

    /**
     *
     * @summary Generate barcode and save on server (from query params or from file with json or xml content)
     * @param request PutBarcodeGenerateFileRequest
     */
    public async putBarcodeGenerateFile(
        request: PutBarcodeGenerateFileRequest
    ): Promise<{ response: HttpResponse; body: ResultImageInfo }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/{name}/generate'.replace('{' + 'name' + '}', String(request.name));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.name' is not null or undefined
        if (request.name == null) {
            throw new Error(
                'Required parameter request.name was null or undefined when calling putBarcodeGenerateFile.'
            );
        }

        // verify required parameter 'request.type' is not null or undefined
        if (request.type == null) {
            throw new Error(
                'Required parameter request.type was null or undefined when calling putBarcodeGenerateFile.'
            );
        }

        // verify required parameter 'request.text' is not null or undefined
        if (request.text == null) {
            throw new Error(
                'Required parameter request.text was null or undefined when calling putBarcodeGenerateFile.'
            );
        }

        if (request.type != null) {
            requestQueryParameters['Type'] = ObjectSerializer.serialize(
                request.type,
                "'Codabar' | 'Code11' | 'Code39Standard' | 'Code39Extended' | 'Code93Standard' | 'Code93Extended' | 'Code128' | 'GS1Code128' | 'EAN8' | 'EAN13' | 'EAN14' | 'SCC14' | 'SSCC18' | 'UPCA' | 'UPCE' | 'ISBN' | 'ISSN' | 'ISMN' | 'Standard2of5' | 'Interleaved2of5' | 'Matrix2of5' | 'ItalianPost25' | 'IATA2of5' | 'ITF14' | 'ITF6' | 'MSI' | 'VIN' | 'DeutschePostIdentcode' | 'DeutschePostLeitcode' | 'OPC' | 'PZN' | 'Code16K' | 'Pharmacode' | 'DataMatrix' | 'QR' | 'Aztec' | 'Pdf417' | 'MacroPdf417' | 'AustraliaPost' | 'Postnet' | 'Planet' | 'OneCode' | 'RM4SCC' | 'DatabarOmniDirectional' | 'DatabarTruncated' | 'DatabarLimited' | 'DatabarExpanded' | 'SingaporePost' | 'GS1DataMatrix' | 'AustralianPosteParcel' | 'SwissPostParcel' | 'PatchCode' | 'DatabarExpandedStacked' | 'DatabarStacked' | 'DatabarStackedOmniDirectional' | 'MicroPdf417' | 'GS1QR' | 'MaxiCode' | 'Code32' | 'DataLogic2of5' | 'DotCode' | 'DutchKIX' | 'UpcaGs1Code128Coupon' | 'UpcaGs1DatabarCoupon' | 'CodablockF' | 'GS1CodablockF' | 'Mailmark' | 'GS1DotCode'"
            );
        }

        if (request.text != null) {
            requestQueryParameters['Text'] = ObjectSerializer.serialize(request.text, 'string');
        }

        if (request.twoDDisplayText != null) {
            requestQueryParameters['TwoDDisplayText'] = ObjectSerializer.serialize(request.twoDDisplayText, 'string');
        }

        if (request.textLocation != null) {
            requestQueryParameters['TextLocation'] = ObjectSerializer.serialize(
                request.textLocation,
                "'Below' | 'Above' | 'None'"
            );
        }

        if (request.textAlignment != null) {
            requestQueryParameters['TextAlignment'] = ObjectSerializer.serialize(
                request.textAlignment,
                "'Left' | 'Center' | 'Right'"
            );
        }

        if (request.textColor != null) {
            requestQueryParameters['TextColor'] = ObjectSerializer.serialize(request.textColor, 'string');
        }

        if (request.fontSizeMode != null) {
            requestQueryParameters['FontSizeMode'] = ObjectSerializer.serialize(
                request.fontSizeMode,
                "'Auto' | 'Manual'"
            );
        }

        if (request.noWrap != null) {
            requestQueryParameters['NoWrap'] = ObjectSerializer.serialize(request.noWrap, 'boolean');
        }

        if (request.resolution != null) {
            requestQueryParameters['Resolution'] = ObjectSerializer.serialize(request.resolution, 'number');
        }

        if (request.resolutionX != null) {
            requestQueryParameters['ResolutionX'] = ObjectSerializer.serialize(request.resolutionX, 'number');
        }

        if (request.resolutionY != null) {
            requestQueryParameters['ResolutionY'] = ObjectSerializer.serialize(request.resolutionY, 'number');
        }

        if (request.dimensionX != null) {
            requestQueryParameters['DimensionX'] = ObjectSerializer.serialize(request.dimensionX, 'number');
        }

        if (request.textSpace != null) {
            requestQueryParameters['TextSpace'] = ObjectSerializer.serialize(request.textSpace, 'number');
        }

        if (request.units != null) {
            requestQueryParameters['Units'] = ObjectSerializer.serialize(
                request.units,
                "'Pixel' | 'Point' | 'Inch' | 'Millimeter'"
            );
        }

        if (request.sizeMode != null) {
            requestQueryParameters['SizeMode'] = ObjectSerializer.serialize(
                request.sizeMode,
                "'None' | 'Nearest' | 'Interpolation'"
            );
        }

        if (request.barHeight != null) {
            requestQueryParameters['BarHeight'] = ObjectSerializer.serialize(request.barHeight, 'number');
        }

        if (request.imageHeight != null) {
            requestQueryParameters['ImageHeight'] = ObjectSerializer.serialize(request.imageHeight, 'number');
        }

        if (request.imageWidth != null) {
            requestQueryParameters['ImageWidth'] = ObjectSerializer.serialize(request.imageWidth, 'number');
        }

        if (request.rotationAngle != null) {
            requestQueryParameters['RotationAngle'] = ObjectSerializer.serialize(request.rotationAngle, 'number');
        }

        if (request.backColor != null) {
            requestQueryParameters['BackColor'] = ObjectSerializer.serialize(request.backColor, 'string');
        }

        if (request.barColor != null) {
            requestQueryParameters['BarColor'] = ObjectSerializer.serialize(request.barColor, 'string');
        }

        if (request.borderColor != null) {
            requestQueryParameters['BorderColor'] = ObjectSerializer.serialize(request.borderColor, 'string');
        }

        if (request.borderWidth != null) {
            requestQueryParameters['BorderWidth'] = ObjectSerializer.serialize(request.borderWidth, 'number');
        }

        if (request.borderDashStyle != null) {
            requestQueryParameters['BorderDashStyle'] = ObjectSerializer.serialize(
                request.borderDashStyle,
                "'Solid' | 'Dash' | 'Dot' | 'DashDot' | 'DashDotDot'"
            );
        }

        if (request.borderVisible != null) {
            requestQueryParameters['BorderVisible'] = ObjectSerializer.serialize(request.borderVisible, 'boolean');
        }

        if (request.enableChecksum != null) {
            requestQueryParameters['EnableChecksum'] = ObjectSerializer.serialize(
                request.enableChecksum,
                "'Default' | 'Yes' | 'No'"
            );
        }

        if (request.enableEscape != null) {
            requestQueryParameters['EnableEscape'] = ObjectSerializer.serialize(request.enableEscape, 'boolean');
        }

        if (request.filledBars != null) {
            requestQueryParameters['FilledBars'] = ObjectSerializer.serialize(request.filledBars, 'boolean');
        }

        if (request.alwaysShowChecksum != null) {
            requestQueryParameters['AlwaysShowChecksum'] = ObjectSerializer.serialize(
                request.alwaysShowChecksum,
                'boolean'
            );
        }

        if (request.wideNarrowRatio != null) {
            requestQueryParameters['WideNarrowRatio'] = ObjectSerializer.serialize(request.wideNarrowRatio, 'number');
        }

        if (request.validateText != null) {
            requestQueryParameters['ValidateText'] = ObjectSerializer.serialize(request.validateText, 'boolean');
        }

        if (request.supplementData != null) {
            requestQueryParameters['SupplementData'] = ObjectSerializer.serialize(request.supplementData, 'string');
        }

        if (request.supplementSpace != null) {
            requestQueryParameters['SupplementSpace'] = ObjectSerializer.serialize(request.supplementSpace, 'number');
        }

        if (request.barWidthReduction != null) {
            requestQueryParameters['BarWidthReduction'] = ObjectSerializer.serialize(
                request.barWidthReduction,
                'number'
            );
        }

        if (request.useAntiAlias != null) {
            requestQueryParameters['UseAntiAlias'] = ObjectSerializer.serialize(request.useAntiAlias, 'boolean');
        }

        if (request.storage != null) {
            requestQueryParameters['storage'] = ObjectSerializer.serialize(request.storage, 'string');
        }

        if (request.folder != null) {
            requestQueryParameters['folder'] = ObjectSerializer.serialize(request.folder, 'string');
        }

        if (request.format != null) {
            requestQueryParameters['format'] = ObjectSerializer.serialize(request.format, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'ResultImageInfo'),
        };
    }

    /**
     *
     * @summary Recognition of a barcode from file on server with parameters in body.
     * @param request PutBarcodeRecognizeFromBodyRequest
     */
    public async putBarcodeRecognizeFromBody(
        request: PutBarcodeRecognizeFromBodyRequest
    ): Promise<{ response: HttpResponse; body: BarcodeResponseList }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/{name}/recognize'.replace('{' + 'name' + '}', String(request.name));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.name' is not null or undefined
        if (request.name == null) {
            throw new Error(
                'Required parameter request.name was null or undefined when calling putBarcodeRecognizeFromBody.'
            );
        }

        // verify required parameter 'request.readerParams' is not null or undefined
        if (request.readerParams == null) {
            throw new Error(
                'Required parameter request.readerParams was null or undefined when calling putBarcodeRecognizeFromBody.'
            );
        }

        if (request.type != null) {
            requestQueryParameters['type'] = ObjectSerializer.serialize(
                request.type,
                "'all' | 'AustraliaPost' | 'Aztec' | 'ISBN' | 'Codabar' | 'Code11' | 'Code128' | 'GS1Code128' | 'Code39Extended' | 'Code39Standard' | 'Code93Extended' | 'Code93Standard' | 'DataMatrix' | 'DeutschePostIdentcode' | 'DeutschePostLeitcode' | 'EAN13' | 'EAN14' | 'EAN8' | 'IATA2of5' | 'Interleaved2of5' | 'ISSN' | 'ISMN' | 'ItalianPost25' | 'ITF14' | 'ITF6' | 'MacroPdf417' | 'Matrix2of5' | 'MSI' | 'OneCode' | 'OPC' | 'PatchCode' | 'Pdf417' | 'MicroPdf417' | 'Planet' | 'Postnet' | 'PZN' | 'QR' | 'MicroQR' | 'RM4SCC' | 'SCC14' | 'SSCC18' | 'Standard2of5' | 'Supplement' | 'UPCA' | 'UPCE' | 'VIN' | 'Pharmacode' | 'GS1DataMatrix' | 'DatabarOmniDirectional' | 'DatabarTruncated' | 'DatabarLimited' | 'DatabarExpanded' | 'SwissPostParcel' | 'AustralianPosteParcel' | 'Code16K' | 'DatabarStackedOmniDirectional' | 'DatabarStacked' | 'DatabarExpandedStacked' | 'CompactPdf417' | 'GS1QR' | 'MaxiCode' | 'MicrE13B' | 'Code32' | 'DataLogic2of5' | 'DotCode' | 'DutchKIX' | 'CodablockF' | 'Mailmark' | 'GS1DotCode' | 'HIBCCode39LIC' | 'HIBCCode128LIC' | 'HIBCAztecLIC' | 'HIBCDataMatrixLIC' | 'HIBCQRLIC' | 'HIBCCode39PAS' | 'HIBCCode128PAS' | 'HIBCAztecPAS' | 'HIBCDataMatrixPAS' | 'HIBCQRPAS'"
            );
        }

        if (request.storage != null) {
            requestQueryParameters['storage'] = ObjectSerializer.serialize(request.storage, 'string');
        }

        if (request.folder != null) {
            requestQueryParameters['folder'] = ObjectSerializer.serialize(request.folder, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            body: ObjectSerializer.serialize(request.readerParams, 'ReaderParams'),
            json: true,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'BarcodeResponseList'),
        };
    }

    /**
     *
     * @summary Generate image with multiple barcodes and put new file on server
     * @param request PutGenerateMultipleRequest
     */
    public async putGenerateMultiple(
        request: PutGenerateMultipleRequest
    ): Promise<{ response: HttpResponse; body: ResultImageInfo }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/{name}/generateMultiple'.replace('{' + 'name' + '}', String(request.name));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.name' is not null or undefined
        if (request.name == null) {
            throw new Error('Required parameter request.name was null or undefined when calling putGenerateMultiple.');
        }

        // verify required parameter 'request.generatorParamsList' is not null or undefined
        if (request.generatorParamsList == null) {
            throw new Error(
                'Required parameter request.generatorParamsList was null or undefined when calling putGenerateMultiple.'
            );
        }

        if (request.format != null) {
            requestQueryParameters['format'] = ObjectSerializer.serialize(request.format, 'string');
        }

        if (request.folder != null) {
            requestQueryParameters['folder'] = ObjectSerializer.serialize(request.folder, 'string');
        }

        if (request.storage != null) {
            requestQueryParameters['storage'] = ObjectSerializer.serialize(request.storage, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            body: ObjectSerializer.serialize(request.generatorParamsList, 'GeneratorParamsList'),
            json: true,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'ResultImageInfo'),
        };
    }
}

export class FileApi {
    protected defaultHeaders: any = {};
    protected _configuration: Configuration;
    private _client: HttpClient;

    constructor(configuration: Configuration) {
        this._configuration = configuration;
        this._client = new HttpClient();
    }

    /**
     *
     * @summary Copy file
     * @param request CopyFileRequest
     */
    public async copyFile(request: CopyFileRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/file/copy/{srcPath}'.replace('{' + 'srcPath' + '}', String(request.srcPath));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.srcPath' is not null or undefined
        if (request.srcPath == null) {
            throw new Error('Required parameter request.srcPath was null or undefined when calling copyFile.');
        }

        // verify required parameter 'request.destPath' is not null or undefined
        if (request.destPath == null) {
            throw new Error('Required parameter request.destPath was null or undefined when calling copyFile.');
        }

        if (request.destPath != null) {
            requestQueryParameters['destPath'] = ObjectSerializer.serialize(request.destPath, 'string');
        }

        if (request.srcStorageName != null) {
            requestQueryParameters['srcStorageName'] = ObjectSerializer.serialize(request.srcStorageName, 'string');
        }

        if (request.destStorageName != null) {
            requestQueryParameters['destStorageName'] = ObjectSerializer.serialize(request.destStorageName, 'string');
        }

        if (request.versionId != null) {
            requestQueryParameters['versionId'] = ObjectSerializer.serialize(request.versionId, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }

    /**
     *
     * @summary Delete file
     * @param request DeleteFileRequest
     */
    public async deleteFile(request: DeleteFileRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/file/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling deleteFile.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        if (request.versionId != null) {
            requestQueryParameters['versionId'] = ObjectSerializer.serialize(request.versionId, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'DELETE',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }

    /**
     *
     * @summary Download file
     * @param request DownloadFileRequest
     */
    public async downloadFile(request: DownloadFileRequest): Promise<{ response: HttpResponse; body: Buffer }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/file/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling downloadFile.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        if (request.versionId != null) {
            requestQueryParameters['versionId'] = ObjectSerializer.serialize(request.versionId, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            encoding: null,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'Buffer'),
        };
    }

    /**
     *
     * @summary Move file
     * @param request MoveFileRequest
     */
    public async moveFile(request: MoveFileRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/file/move/{srcPath}'.replace('{' + 'srcPath' + '}', String(request.srcPath));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.srcPath' is not null or undefined
        if (request.srcPath == null) {
            throw new Error('Required parameter request.srcPath was null or undefined when calling moveFile.');
        }

        // verify required parameter 'request.destPath' is not null or undefined
        if (request.destPath == null) {
            throw new Error('Required parameter request.destPath was null or undefined when calling moveFile.');
        }

        if (request.destPath != null) {
            requestQueryParameters['destPath'] = ObjectSerializer.serialize(request.destPath, 'string');
        }

        if (request.srcStorageName != null) {
            requestQueryParameters['srcStorageName'] = ObjectSerializer.serialize(request.srcStorageName, 'string');
        }

        if (request.destStorageName != null) {
            requestQueryParameters['destStorageName'] = ObjectSerializer.serialize(request.destStorageName, 'string');
        }

        if (request.versionId != null) {
            requestQueryParameters['versionId'] = ObjectSerializer.serialize(request.versionId, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }

    /**
     *
     * @summary Upload file
     * @param request UploadFileRequest
     */
    public async uploadFile(request: UploadFileRequest): Promise<{ response: HttpResponse; body: FilesUploadResult }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/file/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);
        let requestFormParams: any = {};

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling uploadFile.');
        }

        // verify required parameter 'request.file' is not null or undefined
        if (request.file == null) {
            throw new Error('Required parameter request.file was null or undefined when calling uploadFile.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        if (request.file != null) {
            requestFormParams['File'] = request.file;
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
            body: request.file,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'FilesUploadResult'),
        };
    }
}

export class FolderApi {
    protected defaultHeaders: any = {};
    protected _configuration: Configuration;
    private _client: HttpClient;

    constructor(configuration: Configuration) {
        this._configuration = configuration;
        this._client = new HttpClient();
    }

    /**
     *
     * @summary Copy folder
     * @param request CopyFolderRequest
     */
    public async copyFolder(request: CopyFolderRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/folder/copy/{srcPath}'.replace('{' + 'srcPath' + '}', String(request.srcPath));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.srcPath' is not null or undefined
        if (request.srcPath == null) {
            throw new Error('Required parameter request.srcPath was null or undefined when calling copyFolder.');
        }

        // verify required parameter 'request.destPath' is not null or undefined
        if (request.destPath == null) {
            throw new Error('Required parameter request.destPath was null or undefined when calling copyFolder.');
        }

        if (request.destPath != null) {
            requestQueryParameters['destPath'] = ObjectSerializer.serialize(request.destPath, 'string');
        }

        if (request.srcStorageName != null) {
            requestQueryParameters['srcStorageName'] = ObjectSerializer.serialize(request.srcStorageName, 'string');
        }

        if (request.destStorageName != null) {
            requestQueryParameters['destStorageName'] = ObjectSerializer.serialize(request.destStorageName, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }

    /**
     *
     * @summary Create the folder
     * @param request CreateFolderRequest
     */
    public async createFolder(request: CreateFolderRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/folder/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling createFolder.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }

    /**
     *
     * @summary Delete folder
     * @param request DeleteFolderRequest
     */
    public async deleteFolder(request: DeleteFolderRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/folder/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling deleteFolder.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        if (request.recursive != null) {
            requestQueryParameters['recursive'] = ObjectSerializer.serialize(request.recursive, 'boolean');
        }

        let requestOptions: HttpOptions = {
            method: 'DELETE',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }

    /**
     *
     * @summary Get all files and folders within a folder
     * @param request GetFilesListRequest
     */
    public async getFilesList(request: GetFilesListRequest): Promise<{ response: HttpResponse; body: FilesList }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/folder/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling getFilesList.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'FilesList'),
        };
    }

    /**
     *
     * @summary Move folder
     * @param request MoveFolderRequest
     */
    public async moveFolder(request: MoveFolderRequest): Promise<{ response: HttpResponse; body?: any }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/folder/move/{srcPath}'.replace('{' + 'srcPath' + '}', String(request.srcPath));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.srcPath' is not null or undefined
        if (request.srcPath == null) {
            throw new Error('Required parameter request.srcPath was null or undefined when calling moveFolder.');
        }

        // verify required parameter 'request.destPath' is not null or undefined
        if (request.destPath == null) {
            throw new Error('Required parameter request.destPath was null or undefined when calling moveFolder.');
        }

        if (request.destPath != null) {
            requestQueryParameters['destPath'] = ObjectSerializer.serialize(request.destPath, 'string');
        }

        if (request.srcStorageName != null) {
            requestQueryParameters['srcStorageName'] = ObjectSerializer.serialize(request.srcStorageName, 'string');
        }

        if (request.destStorageName != null) {
            requestQueryParameters['destStorageName'] = ObjectSerializer.serialize(request.destStorageName, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'PUT',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return result;
    }
}

export class StorageApi {
    protected defaultHeaders: any = {};
    protected _configuration: Configuration;
    private _client: HttpClient;

    constructor(configuration: Configuration) {
        this._configuration = configuration;
        this._client = new HttpClient();
    }

    /**
     *
     * @summary Get disc usage
     * @param request GetDiscUsageRequest
     */
    public async getDiscUsage(request: GetDiscUsageRequest): Promise<{ response: HttpResponse; body: DiscUsage }> {
        const requestPath = this._configuration.getApiBaseUrl() + '/barcode/storage/disc';
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'DiscUsage'),
        };
    }

    /**
     *
     * @summary Get file versions
     * @param request GetFileVersionsRequest
     */
    public async getFileVersions(
        request: GetFileVersionsRequest
    ): Promise<{ response: HttpResponse; body: FileVersions }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/version/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling getFileVersions.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'FileVersions'),
        };
    }

    /**
     *
     * @summary Check if file or folder exists
     * @param request ObjectExistsRequest
     */
    public async objectExists(request: ObjectExistsRequest): Promise<{ response: HttpResponse; body: ObjectExist }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/exist/{path}'.replace('{' + 'path' + '}', String(request.path));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.path' is not null or undefined
        if (request.path == null) {
            throw new Error('Required parameter request.path was null or undefined when calling objectExists.');
        }

        if (request.storageName != null) {
            requestQueryParameters['storageName'] = ObjectSerializer.serialize(request.storageName, 'string');
        }

        if (request.versionId != null) {
            requestQueryParameters['versionId'] = ObjectSerializer.serialize(request.versionId, 'string');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'ObjectExist'),
        };
    }

    /**
     *
     * @summary Check if storage exists
     * @param request StorageExistsRequest
     */
    public async storageExists(request: StorageExistsRequest): Promise<{ response: HttpResponse; body: StorageExist }> {
        const requestPath =
            this._configuration.getApiBaseUrl() +
            '/barcode/storage/{storageName}/exist'.replace('{' + 'storageName' + '}', String(request.storageName));
        let requestQueryParameters: any = {};
        let requestHeaderParams: any = (Object as any).assign({}, this.defaultHeaders);

        // verify required parameter 'request.storageName' is not null or undefined
        if (request.storageName == null) {
            throw new Error('Required parameter request.storageName was null or undefined when calling storageExists.');
        }

        let requestOptions: HttpOptions = {
            method: 'GET',
            qs: requestQueryParameters,
            headers: requestHeaderParams,
            uri: requestPath,
        };

        await this._configuration.authentication.applyToRequest(requestOptions);

        const result: HttpResult = await this._client.requestAsync(requestOptions);

        return {
            response: result.response,
            body: ObjectSerializer.deserialize(result.body, 'StorageExist'),
        };
    }
}
