name: Try publish to NPM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Use the latest versiob of Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
    - name: Init
      run: make init
    - name: Print current working directory
      run: pwd
    - name: Dry run
      run: npm publish --dry-run
