name: Try publish to NPM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Use the latest versiob of Node.js
      uses: actions/setup-node@v4
      with:
      # Switch node-version: latest (23) to 22 for a while
      # https://github.com/nodejs/node/issues/55410
      # npm pack crash in Node 23
      # node-version: latest
        node-version: 22.x
        cache: 'npm'
    - name: Init
      run: make init
    - name: Dry run
      run: npm publish --dry-run
